{
   "owner" : "anonymous",
   "location" : "perl /nethome/syoung/0.5/bin/apps/snp/cumulativeBam.pl",
   "executor" : "",
   "name" : "cumulativebam",
   "submit" : null,
   "description" : "Cumulatively merge .bam files, can use UCSC bins or user-defined genomic intervals",
   "parameters" : [
      {
         "value" : "500000",
         "discretion" : "",
         "description" : "",
         "params" : "",
         "ordinal" : 1,
         "argument" : "--binlevel",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "binlevel",
         "paramFunction" : ""
      },
      {
         "value" : "hit.bam",
         "discretion" : "",
         "description" : "",
         "argument" : "--filename",
         "ordinal" : 2,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "filename",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/1,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/2,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/3,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/4,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/5,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/6,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/7,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/8,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/9,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/10,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/11,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/12,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/13,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/14,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/15,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/16,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/17,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/18,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/19,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/20,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/21,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/22,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/23,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/24,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/25,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/26,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/27,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/28,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/29,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/30,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/31,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/32,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/33",
         "discretion" : "",
         "description" : "",
         "argument" : "--inputdirs",
         "ordinal" : 3,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "inputdirs",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/cumulative",
         "discretion" : "",
         "description" : "",
         "argument" : "--outputdir",
         "ordinal" : 4,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "outputdir",
         "paramFunction" : ""
      },
      {
         "value" : "human",
         "discretion" : "",
         "description" : "",
         "argument" : "--species",
         "ordinal" : 5,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "species",
         "paramFunction" : ""
      },
      {
         "value" : "novoalign-cumulative",
         "discretion" : "",
         "description" : "",
         "argument" : "--label",
         "ordinal" : 6,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "label",
         "paramFunction" : ""
      },
      {
         "value" : "48",
         "discretion" : "",
         "description" : "",
         "argument" : "--walltime",
         "ordinal" : 7,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "walltime",
         "paramFunction" : ""
      },
      {
         "value" : "LSF",
         "discretion" : "",
         "description" : "",
         "argument" : "--cluster",
         "ordinal" : 8,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "cluster",
         "paramFunction" : ""
      },
      {
         "value" : "small",
         "discretion" : "",
         "description" : "",
         "argument" : "--queue",
         "ordinal" : 9,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "queue",
         "paramFunction" : ""
      },
      {
         "value" : "1",
         "discretion" : "",
         "description" : "",
         "argument" : "--cpus",
         "ordinal" : 10,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "cpus",
         "paramFunction" : ""
      },
      {
         "value" : "2000",
         "discretion" : "",
         "description" : "",
         "argument" : "--maxjobs",
         "ordinal" : 11,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "maxjobs",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/novoalign/cumulative/cumulative.out",
         "discretion" : "",
         "description" : "",
         "argument" : "--stdout",
         "ordinal" : 12,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "stdout",
         "paramFunction" : ""
      }
   ],
   "ordinal" : null,
   "notes" : "",
   "type" : "binner"
}
