---
agua:
  ADMINS: admin
  ADMINUSER: admin
  AGUADIR: agua
  AGUAUSER: agua
  APACHEBINARY: /etc/init.d/apache2
  APACHECONF: /etc/apache2/apache2.conf
  APACHEUSER: www-data
  APPLICATIONS: aquarius-8
  APPSDIR: apps
  APPSPACKAGE: bioapps
  AUTHOR: syoung
  CGIDIR: /var/www/cgi-bin
  CLUSTERTYPE: SGE
  DATA: aquarius-8
  DATADIR: /data
  DOJO: dojo-1.6.1rc2
  EXECUTION_TEMPDIR: /tmp
  FILECACHEDEPTH: '4'
  GUESTACCESS: '1'
  GUESTLOCK: '0'
  GUESTUSER: guest
  HTMLDIR: /var/www/html
  INITCOMPLETE: '0'
  INSTALLDIR: /a
  MODULES: Agua::Admin,Agua::Folders,Agua::Package,Agua::Sharing,Agua::Upload,Agua::View,Agua::Workflow
  OPSPACKAGE: biorepository
  OPSREPO: biorepository
  PRIVATEOPSREPO: private
  REPOSUBDIR: repos
  REPOTYPE: github
  S3BUCKET: https://s3-us-west-1.amazonaws.com/aguadev
  SETUPCOMPLETE: '0'
  SGEROOT: /opt/sge6
  SGEUSER: sgeadmin
  SGEUSERID: '1001'
  SHUTDOWN: 'false'
  SSHPASSWORDLOGIN: NO
  STARCLUSTER: /a/apps/starcluster/bin/starcluster
  STATUS: completed
  TEMPDIR: /tmp
  TESTHTMLDIR: /var/www/html/t
  URLPREFIX: agua
  USERDIR: /home
  VERSION: 0.8.0-alpha.1+build13
  VIRTUALTYPE: aws
applications:
  aquarius-8:
    BINARYDATA: /data/bioapps/binary
    BOWTIE: /data/apps/bowtie/0.12.2
    BOWTIESOURCE: /data/apps/bowtie/0.12.7-src
    CASAVA: /data/apps/casava/1.6.0/bin
    CROSSMATCH: /data/apps/crossmatch/0.990329/cross_match
    CUFFLINKS: /data/apps/cufflinks/0.8.2
    DELTAFILTER: /data/apps/mummer/delta-filter
    ERANGE: /data/pipeline/erange2
    GATK: /data/apps/gatk/1.0.4705
    IAM: /usr/share/iam/1.2.0/bin
    JBROWSE: /data/apps/jbrowse/100511/bin
    MAQ: /data/apps/maq/0.7.1
    MIRA: /data/apps/mira/bin/mira
    NOVOALIGN: /data/apps/novoalign/2.05.33
    NUCMER: /data/apps/mummer/nucmer
    PYTHON: /data/apps/python/2.6.1/bin/python
    REPMASK: /data/apps/erange2/data/repMask/rmask.db
    RUNMAPPING: /data/apps/454/2.0.00.20-64/bin/runMapping
    SAMTOOLS: /data/apps/samtools/0.1.6
    SHOWCOORDS: /data/apps/mummer/show-coords
    SQUASH: /data/apps/GAPipeline/1.5.1/bin/squashGenome
    TANDEMREPEATSFINDER: /data/apps/tandemrepeats/4.04/trf
    TOPHAT: /data/apps/tophat/1.0.12/bin
    VCAKE: /data/apps/vcake/VCAKE_1.0.pl
    VELVET: /data/apps/velvet/velvet
aws:
  ADMINKEY: test
  AVAILABILITYZONE: us-east-1a
  AVAILZONE: us-east-1a
  AWSACCESSKEYID: AKIAIP4XKT35E5KLHSDA
  AWSSECRETACCESSKEY: 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
  DATADEVICE: /dev/sdh
  DATAFILETYPE: ext3
  DATASNAPSHOT: snap-6341b301
  DATAVOLUMESIZE: '200'
  EC2HOME: /usr
  JAVA: /usr/java
  JAVAHOME: /usr
  KEYPAIR: bioinfo1
  REGION: us-east-1
  USERDEVICE: /dev/sdi
  USERFILETYPE: ext3
  USERVOLUMESIZE: '40'
  VOLUMESIZE: '1000'
cluster:
  CANCELJOB: '/opt/sge6/bin/lx24-amd64/qdel -j'
  QSTAT: /opt/sge6/bin/lx24-amd64/qstat
  QSUB: /opt/sge6/bin/lx24-amd64/qsub
  SGEBIN: /opt/sge6/bin/lx24-amd64
  SGEEXECDPORT: '63232'
  SGEQMASTERPORT: '63231'
  SGEROOT: /opt/sge6
  SLEEP: '5'
data:
  aquarius-8:
    BIOAPPS: /data/apps/bioapps
    HUMAN: /data/sequence/human
    HUMANLATESTBUILD: hg19
    JBROWSEDATA: /data/jbrowse/species
    MOUSE: /data/sequence/reference/mouse
    MOUSELATESTBUILD: mm9
    RAT: /data/sequence/reference/rat
    RATLATESTBUILD: rn4
    SAMTOOLSHUMAN: /data/sequence/reference/human/hg19/samtools
    SAMTOOLSMOUSE: /data/sequence/reference/mouse/mm9/samtools
    SAMTOOLSRAT: /data/sequence/reference/rat/rn4/samtools
database:
  CLUSTER_MYSQLDATA: /private/var/mysql
  DATABASE: agua
  DBTYPE: MySQL
  DUMPFILE: bin/sql/dump/agua.dump
  GUESTPASSWORD: guest
  GUESTUSER: guest
  MYSQLDATA: /var/lib/mysql
  PASSWORD: '12345678'
  SESSIONTIMEOUT: '24'
  TESTDATABASE: aguatest
  TESTPASSWORD: '12345678'
  TESTSESSIONID: 12345567890.1234.123
  TESTUSER: testuser
  USER: agua
install:
  AMQPVERSION: 0.1.6
  NODEURL: http://nodejs.org/dist/v0.10.15/node-v0.10.15.tar.gz
  RABBITJS: rabbit.js/example/socketio/server.js
  RABBITVERSION: 0.2.0
  SOCKETVERSION: 0.6.17
openstack:
  KEYPAIR: ~
  OS_AUTH_URL: ~
  OS_PASSWORD: ~
  OS_TENANT_ID: ~
  OS_TENANT_NAME: ~
  OS_USERNAME: ~
packages:
  bioapps:
    AUTHOR: syoung
    DATAVOLUME: aquarius-8
    INSTALLDIR: /a/apps/bioapps
    VERSION: 0.6.0
  biorepository:
    AUTHOR: syoung
    INSTALLDIR: /a/repos/public/agua/biorepository
    VERSION: 0.6.0
  dnaseq:
    0.0.1:
      INSTALLDIR: /a/apps/dnaseq
  s3lib:
    0.0.1:
      INSTALLDIR: /a/apps/s3lib/0.0.1
queue:
  exchange: topicexchange
  exchangetype: topic
  host: 54.144.21.248
  maxjobs:
    admin.QC.DownloadQC: '50'
  password: runrabit%2
  port: '5672'
  user: rabbituser
  vhost: rabbitvhost
starcluster:
  data:
    DEVICE: /dev/sdj
    LOCALDIR: /starclusters
    REMOTEDIR: /data
    SNAPSHOT: snap-4b4fcf26
    VOLUMESIZE: '100'
  images:
    DEFAULT32BIT: ami-1e4dbf77
    DEFAULT64BIT: ami-cea976a7
  mounts:
    DEVICES: /dev/sdh,/dev/sdi,/dev/sdj
    MOUNTBASE: /mnt
    MOUNTPOINTS: /a,/data,/home
    SOURCEDIRS: /a,/data,/home
  nfs:
    MOUNTDPORT: '32767'
    NFSPORT: '2049'
    PORTMAPPORT: '111'
