function RenderBreadCrumb(selectedLi){$("#breadBox").css("height","auto");var crumbs=new Array();
selectedLi.parents("li").each(function(){var link=$(this).children("a");if(link.length>0){crumbs.push(link);
}});var bcElem=$("#breadcrumbs");if(bcElem&&bcElem.length>0){var tlink=$("#nav").find("h3").find("a");
if(tlink.length>0){crumbs.push(tlink);}var hasInitialLis=false;var breadcrumbLis=bcElem.find("li");
if(breadcrumbLis.length>0){var firstBreadcrumbLi=breadcrumbLis[0];if(firstBreadcrumbLi.style.display.toLowerCase()!="none"){hasInitialLis=true;
}else{hasInitialLis=false;}}var lastCrumbPos=0;if(crumbs.length>3){lastCrumbPos=1;
}for(var j=crumbs.length-1;j>=lastCrumbPos;j--){var newLiNode=document.createElement("li");
if((j==crumbs.length-1)&&!hasInitialLis){newLiNode.className="firstChild";}var newANode=document.createElement("a");
newANode.href=crumbs[j].attr("href");newANode.innerHTML=crumbs[j].html();bcElem.append(newLiNode);
newLiNode.appendChild(newANode);}}}if(typeof CDC=="undefined"){var CDC=new Object();
}if(typeof CDC.LeftNav=="undefined"){CDC.LeftNav=new Object();}CDC.LeftNav=function(ulTagId,parentUrl,showSiblings,showChildren,showFourthLevel){var currentLocationWoHash=location.hostname+location.pathname;
if(location.search){currentLocationWoHash=location.hostname+location.pathname+location.search;
}var currentLocationWHash;if(location.hash){if(location.search){currentLocationWHash=location.hostname+location.pathname+location.search+location.hash;
}else{currentLocationWHash=location.hostname+location.pathname+location.hash;}}var directoryDefault=false;
var documentArray=new Array("index.htm","index.html","default.html","default.htm","index.asp","index.aspx","default.asp","default.aspx");
var directoryDefault=false;if(currentLocationWoHash.substr(currentLocationWoHash.length-1,1)=="/"){directoryDefault=true;
}this.attributes=new Array();if(typeof ulTagId=="undefined"){this.setAttribute("CDC_LEFT_NAV_ID","nav-primary");
}else{this.setAttribute("CDC_LEFT_NAV_ID",ulTagId);}if(typeof parentUrl=="undefined"||parentUrl==""){this.setAttribute("parentUrl",this.normalizedUrl(currentLocationWoHash));
this.setAttribute("parentSpecified",false);}else{this.setAttribute("parentUrl",this.normalizedUrl(parentUrl));
this.setAttribute("parentSpecified",true);}if(typeof showSiblings=="undefined"){this.setAttribute("showSiblings",true);
}else{this.setAttribute("showSiblings",showSiblings);}if(typeof showChildren=="undefined"){this.setAttribute("showChildren",true);
}else{this.setAttribute("showChildren",showChildren);}if(typeof showFourthLevel=="undefined"){this.setAttribute("showFourthLevel",true);
}else{this.setAttribute("showFourthLevel",showChildren);}this.setAttribute("documentArray",documentArray);
this.setAttribute("currentLocationWoHash",this.normalizedUrl(currentLocationWoHash));
if(typeof currentLocationWHash!="undefined"){this.setAttribute("currentLocationWHash",this.normalizedUrl(currentLocationWHash));
}this.setAttribute("directoryDefault",directoryDefault);this.setAttribute("CDC_LEFT_NAV_HIDE_CLASS","ulHide");
this.setAttribute("CDC_LEFT_NAV_DISPLAY_CLASS","ulDisplay");this.setAttribute("preProcessTrees",true);
};CDC.LeftNav.prototype={setAttribute:function(name,value){this.attributes[name]=value;
},getAttribute:function(name){return this.attributes[name];},render:function(){var displayClass=this.getAttribute("CDC_LEFT_NAV_DISPLAY_CLASS");
var hideClass=this.getAttribute("CDC_LEFT_NAV_HIDE_CLASS");var showSiblings=this.getAttribute("showSiblings");
var showChildren=this.getAttribute("showChildren");var showFourthLevel=this.getAttribute("showFourthLevel");
var id=this.getAttribute("CDC_LEFT_NAV_ID");var parentUrl=this.getAttribute("parentUrl");
this.setAttribute("currentWoLocation",parentUrl);var leftNav=$("#"+id);if(leftNav.length>0){leftNav.children().find("ul").attr("class",hideClass);
leftNav.children().find("li").attr("class",hideClass);var selectedAnchor=null;var documentArray=this.getAttribute("documentArray");
var directoryDefault=this.getAttribute("directoryDefault");var currentLocationWoHash;
if(this.getAttribute("currentLocationWoHash")){currentLocationWoHash=this.getAttribute("currentLocationWoHash").toLowerCase();
}var currentLocationWHash=this.getAttribute("currentLocationWHash");if(!currentLocationWHash||currentLocationWHash.length==0){currentLocationWHash=currentLocationWoHash;
}var parentSpecified=this.getAttribute("parentSpecified");var found=false;if(parentSpecified){leftNav.find("a").each(function(){if($(this).attr("href")){var curLink=CDC.LeftNav.prototype.normalizedUrl($(this).attr("href")).toLowerCase();
if(curLink==parentUrl){selectedAnchor=$(this);found=true;return false;}}});if(found&&selectedAnchor&&selectedAnchor.parent().length>0){var foundChild=false;
selectedAnchor.parent().find("ul").each(function(){$(this).find("li").each(function(){$(this).find("a").each(function(){if(currentLocationWoHash){if($(this).attr("href")){var curLink=CDC.LeftNav.prototype.normalizedUrl($(this).attr("href")).toLowerCase();
if(curLink==currentLocationWoHash){foundChild=true;return false;}else{if(directoryDefault){for(var j=0;
j<documentArray.length;j++){var doc=documentArray[j];if(curLink==currentLocationWoHash+doc){foundChild=true;
return false;}}}}}}});});});if(showChildren&&!foundChild&&CDC.LeftNav.prototype.normalizedUrl(selectedAnchor.attr("href"))!=currentLocationWHash&&CDC.LeftNav.prototype.normalizedUrl(selectedAnchor.attr("href"))!=currentLocationWoHash){var newUlNode=$(document.createElement("ul"));
var newLiNode=$(document.createElement("li"));var newANode=$(document.createElement("a"));
newANode.attr("href",document.location);newANode.addClass("selected");var newTextNode=$(document.createTextNode(document.title));
var h1=$("h1");if(h1.length>0){newTextNode=$(document.createTextNode(h1.html()));
}newUlNode.append(newLiNode);newLiNode.append(newANode);newANode.append(newTextNode);
selectedAnchor.parent().append(newUlNode);selectedAnchor=newANode;}else{if(showChildren&&(foundChild||CDC.LeftNav.prototype.normalizedUrl(selectedAnchor.attr("href"))==currentLocationWHash||CDC.LeftNav.prototype.normalizedUrl(selectedAnchor.attr("href"))==currentLocationWoHash)){selectedAnchor.addClass("selected");
}}}}else{leftNav.find("a").each(function(){if(currentLocationWoHash){if($(this).attr("href")){var curLink=CDC.LeftNav.prototype.normalizedUrl($(this).attr("href")).toLowerCase();
if(curLink==currentLocationWoHash){$(this).addClass("selected");selectedAnchor=$(this);
found=true;return false;}else{if(directoryDefault){for(var j=0;j<documentArray.length;
j++){var doc=documentArray[j];if(curLink==currentLocationWoHash+doc){$(this).addClass("selected");
selectedAnchor=$(this);found=true;return false;}}}}}}});if(!found&&currentLocationWHash){leftNav.find("a").each(function(){if($(this).attr("href")){var curLink=CDC.LeftNav.prototype.normalizedUrl($(this).attr("href")).toLowerCase();
if(curLink==currentLocationWHash){$(this).addClass("selected");selectedAnchor=$(this);
found=true;return false;}}});}}if(found&&selectedAnchor&&selectedAnchor.length>0){var selectedLi=selectedAnchor.parent();
selectedLi.removeClass(hideClass);selectedLi.addClass(displayClass);selectedLi.parents("ul,li").each(function(){$(this).removeClass(hideClass);
$(this).addClass(displayClass);$(this).siblings("li").removeClass(hideClass);$(this).siblings("li").addClass(displayClass);
});var level=0;selectedLi.parents("ul").each(function(){level++;});if(showSiblings){selectedLi.siblings("li").removeClass(hideClass);
selectedLi.siblings("li").addClass(displayClass);}if(showChildren){var childUl=selectedLi.children("ul");
if(childUl.length>0){childUl.removeClass(hideClass);childUl.addClass(displayClass);
childUl.children("li").removeClass(hideClass);childUl.children("li").addClass(displayClass);
}}RenderBreadCrumb(selectedLi);if(showFourthLevel&&(selectedLi.children("ul").length>0)){var h1Elem=$("#content-main").find("h1");
if(h1Elem){if(level==3&&showChildren||level>3){var newDivNode=$(document.createElement("div"));
newDivNode.attr("id","nav-fourth-level");var newLeftCol=$(document.createElement("div"));
newLeftCol.addClass("c50l");var newRightCol=$(document.createElement("div"));newRightCol.addClass("c50r");
var newLeftList=$(document.createElement("ul"));var newRightList=$(document.createElement("ul"));
newLeftCol.append(newLeftList);newRightCol.append(newRightList);newDivNode.append(newLeftCol);
newDivNode.append(newRightCol);var listLength=0;if(level==3){var parentUl=selectedLi.children("ul");
var listItems=selectedLi.children("ul").children("li");listLength=listItems.length;
if(listLength==1){newLeftList.append(listItems);}else{if(listLength>1){newLeftList.append(listItems.slice(0,Math.ceil(listLength/2)));
newRightList.append(listItems.slice(Math.ceil(listLength/2),listLength));}}parentUl.remove();
}else{var parentUl=selectedLi.parent();var grandParentLi=parentUl.parent();var theLinks=grandParentLi.children("a");
theLinks.addClass("selected");var listItems=parentUl.children("li");listLength=listItems.length;
if(listLength<=1){newLeftList.append(listItems);}else{newLeftList.append(listItems.slice(0,Math.ceil(listLength/2)));
newRightList.append(listItems.slice(Math.ceil(listLength/2),listLength));}var anchors=selectedLi.children("a");
selectedLi.replaceWith('<li><span class="selected">'+anchors.html()+"</span></li>");
parentUl.remove();}h1Elem.after(newDivNode);}}}}}},normalizedUrl:function(url){var result=url;
result=result.replace("http://","");result=result.replace("https://","");result=result.replace(location.hostname,"");
return result.toLowerCase();}};if(typeof CDC.LeftNav.Az=="undefined"){CDC.LeftNav.Az=new Object();
}CDC.LeftNav.Az=function(){return{render:function(singlePageAz){var id="nav-primary";
var hideClass="ulHide";var displayClass="ulDisplay";if(typeof singlePageAz=="undefined"){singlePageAz=false;
}var leftNav=$("#"+id);if(leftNav.length>0){leftNav.children().find("ul").addClass(hideClass);
leftNav.children().find("li").addClass(hideClass);var azLiNode=$("#local-az-link");
if(azLiNode.length>0){azLiNode.addClass(displayClass);azLiNode.find("a").addClass("selected");
RenderBreadCrumb(azLiNode);}}}};}();