{
   "owner" : "anonymous",
   "location" : "/nethome/syoung/0.5/bin/apps/logic/loop.pl",
   "executor" : "",
   "name" : "copysplit",
   "submit" : null,
   "description" : "Link split file subdirectories and generate splitfile.txt file in target directory",
   "parameters" : [
      {
         "value" : "1-33",
         "discretion" : "",
         "description" : "",
         "params" : "",
         "ordinal" : 1,
         "argument" : "--replicates",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "replicates",
         "paramFunction" : ""
      },
      {
         "value" : "distributed",
         "discretion" : "",
         "description" : "",
         "argument" : "--loop",
         "ordinal" : 2,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "loop",
         "paramFunction" : ""
      },
      {
         "value" : "eland-copysplit",
         "discretion" : "",
         "description" : "",
         "argument" : "--looplabel",
         "ordinal" : 3,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "looplabel",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/eland",
         "discretion" : "",
         "description" : "",
         "argument" : "--outdir",
         "ordinal" : 4,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "outdir",
         "paramFunction" : ""
      },
      {
         "value" : "2000",
         "discretion" : "",
         "description" : "",
         "argument" : "--maxjobs",
         "ordinal" : 5,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "maxjobs",
         "paramFunction" : ""
      },
      {
         "value" : "24",
         "discretion" : "",
         "description" : "",
         "argument" : "--walltime",
         "ordinal" : 6,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "walltime",
         "paramFunction" : ""
      },
      {
         "value" : "small",
         "discretion" : "",
         "description" : "",
         "argument" : "--queue",
         "ordinal" : 7,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "queue",
         "paramFunction" : ""
      },
      {
         "value" : "LSF",
         "discretion" : "",
         "description" : "",
         "argument" : "--cluster",
         "ordinal" : 8,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "cluster",
         "paramFunction" : ""
      },
      {
         "value" : "1",
         "discretion" : "",
         "description" : "",
         "argument" : "--cpus",
         "ordinal" : 9,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "cpus",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/eland/loop-copysplit.out",
         "discretion" : "",
         "description" : "",
         "argument" : "--loopout",
         "ordinal" : 10,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "loopout",
         "paramFunction" : ""
      },
      {
         "value" : "/nethome/syoung/0.5/bin/apps/aligners/copySplitfiles.pl",
         "discretion" : "",
         "description" : "",
         "argument" : "--executable",
         "ordinal" : 11,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "executable",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/eland/%REPLICATE%",
         "discretion" : "",
         "description" : "",
         "argument" : "--source",
         "ordinal" : 12,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "source",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/bowtie/%REPLICATE%",
         "discretion" : "",
         "description" : "",
         "argument" : "--target",
         "ordinal" : 13,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "target",
         "paramFunction" : ""
      },
      {
         "value" : "link",
         "discretion" : "",
         "description" : "",
         "argument" : "--mode",
         "ordinal" : 14,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "mode",
         "paramFunction" : ""
      }
   ],
   "ordinal" : null,
   "notes" : "",
   "type" : null
}
