---
abstract: 'a simple wrapper round the OAuth protocol'
author:
  - 'Simon Wistow, C<<simon@thegestalt.org >>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OAuth-Simple
provides:
  Net::OAuth::Simple:
    file: lib/Net/OAuth/Simple.pm
    version: 1.5
requires:
  CGI: 0
  Crypt::SSLeay: 0
  LWP::UserAgent: 0
  Net::OAuth: 0.27
  Test::More: 0.06
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.5
