---
abstract: 'Simple interface to the Google Analytics Core Reporting API'
author:
  - 'Nick Wellnhofer <wellnhofer@aevum.de>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Google-Analytics
requires:
  Class::XSAccessor: 1.05
  JSON: 0
  LWP::UserAgent: 0
  URI: 0
  perl: 5.008
resources:
  repository: http://github.com/nwellnhof/Net-Google-Analytics
version: 3.00
