{
   "parameters" : [
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/100M/simpleheader/yoruba1-1.reads_1.sequence.txt",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--inputfiles",
         "ordinal" : 1,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "inputfiles",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/100M/simpleheader/yoruba1-1.reads_2.sequence.txt",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--matefiles",
         "ordinal" : 2,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "matefiles",
         "paramFunction" : ""
      },
      {
         "value" : "human",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--species",
         "ordinal" : 3,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "species",
         "paramFunction" : ""
      },
      {
         "value" : "200",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--distance",
         "ordinal" : 4,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "distance",
         "paramFunction" : ""
      },
      {
         "value" : "bowtie-1",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--label",
         "ordinal" : 5,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "label",
         "paramFunction" : ""
      },
      {
         "value" : "1000",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--maxjobs",
         "ordinal" : 6,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "maxjobs",
         "paramFunction" : ""
      },
      {
         "value" : "24",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--walltime",
         "ordinal" : 7,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "walltime",
         "paramFunction" : ""
      },
      {
         "value" : "",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--clean",
         "ordinal" : 8,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "clean",
         "paramFunction" : ""
      },
      {
         "value" : "small",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--queue",
         "ordinal" : 9,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "queue",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/bowtie/1",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--outputdir",
         "ordinal" : 10,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "outputdir",
         "paramFunction" : ""
      },
      {
         "value" : "/nethome/bioinfo/data/sequence/chromosomes/human/hg19/bowtie/chr22",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--reference",
         "ordinal" : 11,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "reference",
         "paramFunction" : ""
      },
      {
         "value" : "LSF",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--cluster",
         "ordinal" : 12,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "cluster",
         "paramFunction" : ""
      },
      {
         "value" : "1",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--cpus",
         "ordinal" : 13,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "cpus",
         "paramFunction" : ""
      },
      {
         "value" : "100000",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--reads",
         "ordinal" : 14,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "reads",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/bowtie/1/bowtie.out",
         "paramArgs" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--stdout",
         "ordinal" : 15,
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "stdout",
         "paramFunction" : ""
      }
   ],
   "owner" : "anonymous",
   "location" : "/nethome/bioinfo/apps/agua/0.5/bin/apps/aligners/BOWTIE.pl",
   "notes" : "",
   "executor" : 0,
   "name" : "bowtie",
   "type" : "aligner",
   "description" : ""
}
