{
   "parameters" : [
      {
         "value" : "2500000",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "params" : "",
         "ordinal" : "",
         "argument" : "--binlevel",
         "format" : "",
         "type" : "",
         "category" : "",
         "param" : "binlevel",
         "paramFunction" : ""
      },
      {
         "value" : "LSF",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--cluster",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "cluster",
         "paramFunction" : ""
      },
      {
         "value" : "snp130",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--dbsnp",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "dbsnp",
         "paramFunction" : ""
      },
      {
         "value" : "/nethome/bioinfo/apps/agua/0.5/bin/apps/snp/SAV.pl",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--executable",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "executable",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/eland/%REPLICATE%",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--inputdirs",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "inputdirs",
         "paramFunction" : ""
      },
      {
         "value" : "parallel",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--loop",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "loop",
         "paramFunction" : ""
      },
      {
         "value" : "1000",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--maxjobs",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "maxjobs",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/eland/cumulative4",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--outputdir",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "outputdir",
         "paramFunction" : ""
      },
      {
         "value" : "small",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--queue",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "queue",
         "paramFunction" : ""
      },
      {
         "value" : "/nethome/bioinfo/data/sequence/chromosomes/human/hg19/fasta/chr22",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--referencedir",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "referencedir",
         "paramFunction" : ""
      },
      {
         "value" : "1-33",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--replicates",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "replicates",
         "paramFunction" : ""
      },
      {
         "value" : "human",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--species",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "species",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/eland/cumulative4/snp130-%REPLICATE%",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--tempfile",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "tempfile",
         "paramFunction" : ""
      },
      {
         "value" : "24",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--walltime",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "walltime",
         "paramFunction" : ""
      }
   ],
   "owner" : "anonymous",
   "location" : "/nethome/bioinfo/apps/agua/0.5/bin/apps/logic/loop.pl",
   "notes" : "",
   "executor" : 0,
   "name" : "sav",
   "type" : "cluster",
   "description" : ""
}
