{
   "parameters" : [
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/cumulative3/unbin.out",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "params" : "",
         "ordinal" : "",
         "argument" : "&>",
         "format" : "",
         "type" : "",
         "category" : "",
         "param" : "&>",
         "paramFunction" : ""
      },
      {
         "value" : "2500000",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--binlevel",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "binlevel",
         "paramFunction" : ""
      },
      {
         "value" : "LSF",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--cluster",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "cluster",
         "paramFunction" : ""
      },
      {
         "value" : "1",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--cpus",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "cpus",
         "paramFunction" : ""
      },
      {
         "value" : "hit.bam",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--filename",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "filename",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/1,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/2,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/3,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/4,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/5,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/6,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/7,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/8,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/9,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/10,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/11,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/12,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/13,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/14,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/15,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/16,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/17,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/18,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/19,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/20,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/21,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/22,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/23,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/24,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/25,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/26,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/27,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/28,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/29,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/30,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/31,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/32,/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/33",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--inputdirs",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "inputdirs",
         "paramFunction" : ""
      },
      {
         "value" : "1000",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--maxjobs",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "maxjobs",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/maq/cumulative3",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--outputdir",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "outputdir",
         "paramFunction" : ""
      },
      {
         "value" : "small",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--queue",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "queue",
         "paramFunction" : ""
      },
      {
         "value" : "sav",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--suffix",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "suffix",
         "paramFunction" : ""
      },
      {
         "value" : "48",
         "args" : "",
         "discretion" : "",
         "description" : "",
         "argument" : "--walltime",
         "ordinal" : "",
         "params" : "",
         "format" : "",
         "category" : "",
         "type" : "",
         "param" : "walltime",
         "paramFunction" : ""
      }
   ],
   "owner" : "anonymous",
   "location" : "perl /nethome/bioinfo/apps/agua/0.5/bin/apps/snp/unbin.pl",
   "notes" : "",
   "executor" : 0,
   "name" : "unbinsav",
   "type" : "cluster",
   "description" : ""
}
