{
   "owner" : "anonymous",
   "location" : "/nethome/syoung/0.5/bin/apps/logic/loop.pl",
   "executor" : "",
   "name" : "binbam",
   "submit" : null,
   "description" : "Bin a .bam file into smaller .bam files covering UCSC bins or user-defined genomic intervals",
   "parameters" : [
      {
         "value" : "1-33",
         "discretion" : "",
         "description" : "",
         "params" : "",
         "ordinal" : 1,
         "argument" : "--replicates",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "replicates",
         "paramFunction" : ""
      },
      {
         "value" : "parallel",
         "discretion" : "",
         "description" : "",
         "argument" : "--loop",
         "ordinal" : 2,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "loop",
         "paramFunction" : ""
      },
      {
         "value" : "/nethome/syoung/0.5/bin/apps/snp/binBam.pl",
         "discretion" : "",
         "description" : "",
         "argument" : "--executable",
         "ordinal" : 3,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "executable",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/eland/%REPLICATE%",
         "discretion" : "",
         "description" : "",
         "argument" : "--inputdirs",
         "ordinal" : 4,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "inputdirs",
         "paramFunction" : ""
      },
      {
         "value" : "500000",
         "discretion" : "",
         "description" : "",
         "argument" : "--binlevel",
         "ordinal" : 5,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "binlevel",
         "paramFunction" : ""
      },
      {
         "value" : "chr22",
         "discretion" : "",
         "description" : "",
         "argument" : "--reference",
         "ordinal" : 6,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "reference",
         "paramFunction" : ""
      },
      {
         "value" : "2000",
         "discretion" : "",
         "description" : "",
         "argument" : "--maxjobs",
         "ordinal" : 7,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "maxjobs",
         "paramFunction" : ""
      },
      {
         "value" : "48",
         "discretion" : "",
         "description" : "",
         "argument" : "--walltime",
         "ordinal" : 8,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "walltime",
         "paramFunction" : ""
      },
      {
         "value" : "small",
         "discretion" : "",
         "description" : "",
         "argument" : "--queue",
         "ordinal" : 9,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "queue",
         "paramFunction" : ""
      },
      {
         "value" : "LSF",
         "discretion" : "",
         "description" : "",
         "argument" : "--cluster",
         "ordinal" : 10,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "cluster",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/eland/%REPLICATE%/binbam.out",
         "discretion" : "",
         "description" : "",
         "argument" : "--stdout",
         "ordinal" : 11,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "stdout",
         "paramFunction" : ""
      },
      {
         "value" : "/scratch/syoung/base/pipeline/SRA/NA18507/SRP000239/sampled/200bp/chr22/eland/loop-binbam.out",
         "discretion" : "",
         "description" : "",
         "argument" : "--loopout",
         "ordinal" : 12,
         "params" : "",
         "format" : "",
         "paramfile" : "",
         "category" : "",
         "type" : "",
         "param" : "loopout",
         "paramFunction" : ""
      }
   ],
   "ordinal" : null,
   "notes" : "",
   "type" : "binner"
}
