pref("extension.firegoose.website.Test_R_page", false);
pref("extension.firegoose.website.GaggleStore", false);
pref("extension.firegoose.website.Page_Goose", false);
pref("extension.firegoose.website.Metlin", false);
pref("extension.firegoose.website.EGRIN", false);
pref("extension.firegoose.website.t1dbase", false);
pref("extension.firegoose.website.api", false);
pref("extension.firegoose.website.PIPE2", false);
pref("extension.firegoose.autoStartBoss", false);
