// /web/private/htdocs/staff/sponomar/TEST/corehtml/jsutils/drag_n_drop.1.js.orig

function Dnd(_oElementToDrag,sPosition){this.oElementToDrag=_oElementToDrag;this.oContainerDim=0;this.oContainer=0;this.constraint={vert:!utils.hasClass(_oElementToDrag,"horiz"),horiz:!utils.hasClass(_oElementToDrag,"vert"),clip:utils.hasClass(_oElementToDrag,"clip"),pos:utils.hasClass(_oElementToDrag,"pos"),snap:utils.hasClass(_oElementToDrag,"snap"),d:{w:50,h:50}}
this.deltaX=0;this.deltaY=0;if(this.constraint.pos||this.constraint.snap){this.constraint.d.w=0;this.constraint.d.h=0;}
utils.addEvent(_oElementToDrag,"mousedown",downHandler,false);var oThis=this;function downHandler(e){if(Dnd.isActive)return;Dnd.isActive=true;var oTarget=utils.getTargetObj(e);var sTargetTagName=oTarget.tagName;if("INPUT"==sTargetTagName||"SELECT"==sTargetTagName||"TEXTAREA"==sTargetTagName||"BUTTON"==sTargetTagName||utils.hasClass(oTarget,"nodrag")){Dnd.isActive=false;return;}
oThis.Start(e);if(sPosition){_oElementToDrag.style.position=sPosition;}else if(_oElementToDrag.style.position!="relative"&&!utils.hasClass(_oElementToDrag,"cloned")){_oElementToDrag.style.position="relative";}
if(oThis.constraint.pos||oThis.constraint.clip||oThis.constraint.snap){oThis.oContainer=utils.getParent(oThis.oElementToDrag);oThis.oContainerDim=utils.getXY(oThis.oContainer);var b=utils.getBorders(oThis.oContainer);if(!b.isInner){oThis.oContainerDim.w-=parseInt(b.l)+parseInt(b.r);oThis.oContainerDim.h-=parseInt(b.r)+parseInt(b.t);}}
if(utils.hasClass(this,"clone")){utils.removeEvent(_oElementToDrag,"mousedown",downHandler,false);oThis.oElementToDrag=_oElementToDrag.cloneNode(true);utils.insertAfter(_oElementToDrag.parentNode,oThis.oElementToDrag,_oElementToDrag);oThis.oElementToDrag.Dnd=new Dnd(oThis.oElementToDrag);utils.removeClass(oThis.oElementToDrag,"clone");utils.addClass(oThis.oElementToDrag,"cloned");utils.addEvent(_oElementToDrag,"mousedown",downHandler,false);oThis.oElementToDrag.style.position="absolute";var xy=utils.getXY(_oElementToDrag);oThis.oElementToDrag.style.left=(xy.x+10)+"px";oThis.oElementToDrag.style.top=(xy.y+10)+"px";}else{oThis.oElementToDrag=_oElementToDrag;}
if(parseInt(oThis.oElementToDrag.style.left)){oThis.deltaX=e.clientX-parseInt(oThis.oElementToDrag.style.left);}else oThis.deltaX=e.clientX;if(parseInt(oThis.oElementToDrag.style.top)){oThis.deltaY=e.clientY-parseInt(oThis.oElementToDrag.style.top);}else oThis.deltaY=e.clientY;utils.addEvent(document,"mousemove",moveHandler,false);utils.addEvent(document,"mouseup",upHandler,false);utils.preventDefault(e);utils.addClass(oThis.oElementToDrag,"moving");function moveHandler(e){utils.preventDefault(e);oThis.correctDnd(e.clientX-oThis.deltaX,e.clientY-oThis.deltaY);if(oThis.Drag(e)){upHandler(e);}
return true;}
function upHandler(e){utils.removeEvent(document,"mousemove",moveHandler,false);utils.removeEvent(document,"mouseup",upHandler,false);utils.preventDefault(e);utils.removeClass(oThis.oElementToDrag,"moving");oThis.Drop(e);Dnd.isActive=false;return true;}}}
Dnd.prototype.correctDnd=function(x,y){var X=x;var Y=y;if(this.constraint.pos||this.constraint.clip||this.constraint.snap){var d=utils.getXY(this.oElementToDrag);d.x=x;d.y=y;var r=this.oContainerDim;if(this.constraint.snap){if(d.x>0)X=0;if(d.y>0)Y=0;if(d.y+(d.h-r.h)<0)Y=r.h-d.h;if(d.x+(d.w-r.w)<0)X=r.w-d.w;}else if(this.constraint.pos){if(d.x<0)X=0;if(d.y<0)Y=0;if(d.y+(d.h-r.h)>0)Y=r.h-d.h;if(d.x+(d.w-r.w)>0)X=r.w-d.w;}else if(this.constraint.clip){if(d.x+this.constraint.d.w<0)X=-this.constraint.d.w;if(d.y+this.constraint.d.h<0)Y=-this.constraint.d.h;if(d.y+(d.h-r.h)>this.constraint.d.h)Y=r.h-d.h+this.constraint.d.h;if(d.x+(d.w-r.w)>this.constraint.d.w)X=r.w-d.w+this.constraint.d.w;}}
if(this.constraint.horiz){this.oElementToDrag.style.left=X+"px";}else{this.oElementToDrag.style.left="0px";}
if(this.constraint.vert){this.oElementToDrag.style.top=Y+"px";}else{this.oElementToDrag.style.top="0px";}}
Dnd.prototype.Start=function(){}
Dnd.prototype.Drag=function(){}
Dnd.prototype.Drop=function(){}
Dnd.prototype.Move=function(x,y){if(this.oElementToDrag){if(this.constraint.pos||this.constraint.clip||this.constraint.snap){this.oContainer=utils.getParent(this.oElementToDrag);this.oContainerDim=utils.getXY(this.oContainer);}
this.correctDnd(x,y);this.Drag();}}
Dnd.prototype.MoveBy=function(dx,dy){if(this.oElementToDrag){if(this.constraint.pos||this.constraint.clip||this.constraint.snap){this.oContainer=utils.getParent(this.oElementToDrag);this.oContainerDim=utils.getXY(this.oContainer);}
this.correctDnd(parseInt(this.oElementToDrag.style.left)+dx,parseInt(this.oElementToDrag.style.top)+dy);this.Drag();}}
Dnd.isActive=false;