forge "http://forge.puppetlabs.com"

mod "stdlib",
   :git => "git://github.com/puppetlabs/puppetlabs-stdlib.git"

mod "mysql", "2.1.0",
   :git => "git://github.com/puppetlabs/puppetlabs-mysql.git"

mod "apache", "0.10.0",
   :git => "git://github.com/puppetlabs/puppetlabs-apache.git"

