function OAS_RICH(position) {
if (position == 'Top') {
document.write ('<!-- \n');
document.write ('Support: http://oas.biomedcentral.com#biomed/Alma-Biomed-Lead-2#Alma-Biomed-Lead-2#Alma-Biomed-Lead-2.html#c7b8b#1239108553#437#S#Top#www.scfbm.org/article/sourcecodebiolmed##\n');
document.write ('--><script id="extFlashTop1" type="text/javascript" src="http://realmedia-a592.d4p.net/6/592/1130/0001/oas-eu.247realmedia.com/RealMedia/ads/Creatives/biomed/Alma-Biomed-Lead-2/TFSMflashobject.js"></script>\n');
document.write ('<SCRIPT Language="JavaScript">\n');
document.write ('<!--\n');
document.write ('if(!document.body)\n');
document.write ('document.write("<html><body>");\n');
document.write ('OASd = document;\n');
document.write ('var plug = false;\n');
document.write ('var flashVersion = -1;\n');
document.write ('var minFlashVersion = 6;\n');
document.write ('if(navigator.plugins != null && navigator.plugins.length > 0){flashVersion =(navigator.plugins["Shockwave Flash 2.0"] || navigator.plugins["Shockwave Flash"]) ? navigator.plugins["Shockwave Flash" +(navigator.plugins["Shockwave Flash 2.0"] ? " 2.0" : "")].description.split(" ")[2].split(".")[0] : -1;\n');
document.write ('plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if(navigator.userAgent.toLowerCase().indexOf("webtv/2.6") != -1){flashVersion = 4;plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if(navigator.userAgent.toLowerCase().indexOf("webtv/2.5") != -1){flashVersion = 3;plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if(navigator.userAgent.toLowerCase().indexOf("webtv") != -1){flashVersion = 2;plug = flashVersion >= minFlashVersion;}\n');
document.write ('else if((navigator.appVersion.indexOf("MSIE") != -1) &&(navigator.appVersion.toLowerCase().indexOf("win") != -1) &&(navigator.userAgent.indexOf("Opera") == -1)){var oasobj;\n');
document.write ('var exc;\n');
document.write ('try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");\n');
document.write ('flashVersion = oasobj.GetVariable("$version");} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");\n');
document.write ('version = "WIN 6,0,21,0"; \n');
document.write ('oasobj.AllowScriptAccess = "always";\n');
document.write ('flashVersion = oasobj.GetVariable("$version");} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");\n');
document.write ('flashVersion = oasobj.GetVariable("$version");} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");\n');
document.write ('flashVersion = "WIN 3,0,18,0";} catch(exc){try{oasobj = new ActiveXObject("ShockwaveFlash.ShockwaveFlash");\n');
document.write ('flashVersion = "WIN 2,0,0,11";} catch(exc){flashVersion = -1;}}}}}\n');
document.write ('plug =(flashVersion != -1)? flashVersion.split(" ")[1].split(",")[0] >= minFlashVersion : false;}\n');
document.write ('\n');
document.write ('if(plug)\n');
document.write ('{\n');
document.write ('document.write("<div id=\\');
document.write ('"FinContentTop1\\');
document.write ('"></div>");\n');
document.write ('function loadFlashTop1(){\n');
document.write ('	if(navigator.userAgent.indexOf("MSIE") != -1 && navigator.userAgent.indexOf("Opera") == -1){\n');
document.write ('	\n');
document.write ('		if (extFlashTop1.readyState == "complete")\n');
document.write ('  		{\n');
document.write ('	   		FlashObject("http://realmedia-a592.d4p.net/6/592/1130/0001/oas-eu.247realmedia.com/RealMedia/ads/Creatives/biomed/Alma-Biomed-Lead-2/novoseek_728x90_02_flash08.swf?clickTag=http://oas.biomedcentral.com/RealMedia/ads/click_lx.ads/www.scfbm.org/article/sourcecodebiolmed/1418541634/Top/biomed/Alma-Biomed-Lead-2/Alma-Biomed-Lead-2.html/34386665393030393439386238646230?%22bioinformatics+workflows%22+pise+review", "OAS_AD_Top", "width=728 height=90", "opaque", "clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" ,"6", "FinContentTop1");\n');
document.write ('			extFlashTop1.onreadystatechange = "";\n');
document.write ('		}\n');
document.write ('	\n');
document.write ('		extFlashTop1.onreadystatechange = loadFlashTop1;\n');
document.write ('	}\n');
document.write ('	else\n');
document.write ('	{\n');
document.write ('           OASfp=" Menu=FALSE swModifyReport=TRUE width=728 height=90 ";\n');
document.write ('           OASd.write("<object id=\\');
document.write ('"techsource_Top\\');
document.write ('" classid=\\');
document.write ('"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\\');
document.write ('" codebase=\\');
document.write ('"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0\\');
document.write ('""+OASfp+">");\n');
document.write ('           OASd.write("<param name=src value=\\');
document.write ('"http://realmedia-a592.d4p.net/6/592/1130/0001/oas-eu.247realmedia.com/RealMedia/ads/Creatives/biomed/Alma-Biomed-Lead-2/novoseek_728x90_02_flash08.swf\\');
document.write ('"><param name=allowScriptAccess value=always><param name=quality value=autohigh><param name=loop value=true><param name=play value=true><param name=menu value=false><param name=wmode value=opaque><param name=FlashVars value=\\');
document.write ('"clickTag=http://oas.biomedcentral.com/RealMedia/ads/click_lx.ads/www.scfbm.org/article/sourcecodebiolmed/1418541634/Top/biomed/Alma-Biomed-Lead-2/Alma-Biomed-Lead-2.html/34386665393030393439386238646230?%22bioinformatics+workflows%22+pise+review\\');
document.write ('">");\n');
document.write ('           OASd.write("<embed src=\\');
document.write ('"http://realmedia-a592.d4p.net/6/592/1130/0001/oas-eu.247realmedia.com/RealMedia/ads/Creatives/biomed/Alma-Biomed-Lead-2/novoseek_728x90_02_flash08.swf\\');
document.write ('""+OASfp+"pluginspage=\\');
document.write ('"http://www.macromedia.com/shockwave\\');
document.write ('" type=\\');
document.write ('"application/x-shockwave-flash\\');
document.write ('" width=728 height=90 PLAY=true LOOP=true QUALITY=autohigh WMODE=opaque FlashVars=\\');
document.write ('"clickTag=http://oas.biomedcentral.com/RealMedia/ads/click_lx.ads/www.scfbm.org/article/sourcecodebiolmed/1418541634/Top/biomed/Alma-Biomed-Lead-2/Alma-Biomed-Lead-2.html/34386665393030393439386238646230?%22bioinformatics+workflows%22+pise+review\\');
document.write ('" allowScriptAccess=always>");\n');
document.write ('           OASd.write("</embed></object>");\n');
document.write ('        }\n');
document.write ('\n');
document.write ('}\n');
document.write ('	loadFlashTop1();\n');
document.write ('}\n');
document.write ('else\n');
document.write ('{\n');
document.write ('OASd.write("<a href=\\');
document.write ('"http://oas.biomedcentral.com/RealMedia/ads/click_lx.ads/www.scfbm.org/article/sourcecodebiolmed/1418541634/Top/biomed/Alma-Biomed-Lead-2/Alma-Biomed-Lead-2.html/34386665393030393439386238646230?%22bioinformatics+workflows%22+pise+review\\');
document.write ('" target=\\');
document.write ('"_blank\\');
document.write ('"><img src=\\');
document.write ('"http://realmedia-a592.d4p.net/6/592/1130/0001/oas-eu.247realmedia.com/RealMedia/ads/Creatives/biomed/Alma-Biomed-Lead-2/banner_alternativo2.gif\\');
document.write ('" width=728 height=90 border=0 alt=\\');
document.write ('"\\');
document.write ('"></a>");}\n');
document.write ('if(!document.body)\n');
document.write ('document.write("</body></html>");\n');
document.write ('//-->\n');
document.write ('</SCRIPT>');
}
if (position == 'Bottom') {
document.write ('<script type="text/javascript"><!--\n');
document.write ('google_ad_client = "pub-8287243681099367";\n');
document.write ('/* 728x90, created 3/5/09 */\n');
document.write ('google_ad_slot = "2716523086";\n');
document.write ('google_ad_width = 728;\n');
document.write ('google_ad_height = 90;\n');
document.write ('//-->\n');
document.write ('</script>\n');
document.write ('<script type="text/javascript"\n');
document.write ('src="http://pagead2.googlesyndication.com/pagead/show_ads.js">\n');
document.write ('</script>');
}
}
