// /web/private/htdocs/staff/sponomar/TEST/corehtml/jsutils/tile.1.js.orig

utils.jsLoader.load(["notify.1.js","drag_n_drop.1.js"]);function TileData(){this.NAME="TileData";}
TileData.prototype.Init=function(oImg,oNotifier){var oThis=this;this.oNotifier=oNotifier;this.iWinBorder=0;this.bIsTiled=true;this.bIsStaticImage=false;this.sUrl="";this.sPrefix="";this.oTile={w:0,h:0};this.oPicture={w:1,h:1,x:0,y:0,dx:50,dy:50};this.oViewport={w:500,h:300,x:0,y:0,cx:0,cy:0};this.oPanorama={w:1,h:1,x:0,y:0,bIsVisible:true,img:oImg,border:6};this.oPanorama.x=this.oPanorama.y=this.oPanorama.border;this.oPan={w:1,h:1,x:0,y:0};this.iScaleIndex=0;this.oScales=[];this.fScale=-1.0;this.fViewportPanorama=3;this.fPicturePanorama=0.0;var a=this.oPanorama.img.getAttribute("rel");if(!a)a=this.oPanorama.img.src+"";a=a.split("?");this.sUrl=a[0];a=a[1].split("&");var tmp;for(var i=0;i<a.length;i++){if(a[i].indexOf("x=")==0){tmp=a[i].split("=");this.oViewport.cx=parseFloat(tmp[1]/100);if(this.oViewport.cx>1)
this.oViewport.cx=1;else
if(this.oViewport.cx<0)
this.oViewport.cx=0;}else if(a[i].indexOf("y=")==0){tmp=a[i].split("=");this.oViewport.cy=parseFloat(tmp[1]/100);if(this.oViewport.cy>1)
this.oViewport.cy=1;else
if(this.oViewport.cy<0)
this.oViewport.cy=0;}else if(a[i].indexOf("w=")==0){tmp=a[i].split("=");this.oViewport.w=parseFloat(tmp[1]);}else if(a[i].indexOf("h=")==0){tmp=a[i].split("=");this.oViewport.h=parseFloat(tmp[1]);}else if(a[i].indexOf("scale=")==0){tmp=a[i].split("=");this.fScale=parseFloat(tmp[1]/100);if(this.fScale>1||this.fScale<0)this.fScale=1;}else if(a[i].indexOf("pan=")==0){tmp=a[i].split("=");this.oPanorama.bVisible=tmp[1]>0;}else{this.Parse(a[i]);}}
this.oNotifier.setListener(oThis,"resize",function(oListener,oCoord){oThis.oViewport.w=oCoord.w;oThis.oViewport.h=oCoord.h;oThis.Calculate();});this.oNotifier.setListener(oThis,"scale",function(oListener,iScaleIndex){oThis.bIsStaticImage=iScaleIndex==oThis.oScales.length-1;});}
TileData.prototype.Calculate=function(){var kw=this.oPicture.w/this.oViewport.w;var kh=this.oPicture.h/this.oViewport.h;var k=(kw>kh?kw:kh)*this.fViewportPanorama;this.oPanorama.w=parseInt(this.oPicture.w/k);this.oPanorama.h=parseInt(this.oPicture.h/k);this.fPicturePanorama=this.oPicture.w/this.oPanorama.w;this.oPan.w=parseInt(this.oViewport.w/k);if(this.oPan.w>this.oPanorama.w)
this.oPan.w=this.oPanorama.w;this.oPan.h=parseInt(this.oViewport.h/k);if(this.oPan.h>this.oPanorama.h)
this.oPan.h=this.oPanorama.h;this.bIsStaticImage=this.iScaleIndex==this.oScales.length-1;this.oNotifier.Notify(this,"data-is-ready","");}
TileData.prototype.Parse=function(arr){}
TileData.prototype.GetTileUrl=function(row,col){}
TileData.prototype.GetFitUrl=function(){}
TileData.prototype.GetTileId=function(row,col){return this.sPrefix+"_"+row+"_"+col;}
function Tile(TileData,oNotifier){this.NAME="Tile";var oThis=this;this.oTileData=TileData;this.oNotifier=oNotifier;oThis.oCanvas=document.createElement("div");this.oCanvas.className="viewport";this.oCanvas.ondrag=function(){return false;};this.oCanvas.onselectstart=function(){return false;};this.Timer=0;this.Delta=1;this.bForceRedraw=true;this.bFirstTimeDraw=false;this.oNotifier.setListener(oThis,"data-is-ready",function(){var oTileData=oThis.oTileData;oThis.oCanvas.style.width=oTileData.oViewport.w+"px";oThis.oCanvas.style.height=oTileData.oViewport.h+"px";oThis.oCanvas.style.position="relative";if(!oThis.oDnd){oThis.oDnd=document.createElement("div");oThis.oDnd.className="dnd snap";oThis.oDnd.style.position="relative";oThis.oDnd.dnd=new Dnd(oThis.oDnd);oThis.oCanvas.appendChild(oThis.oDnd);utils.addEvent(oThis.oDnd,"dblclick",function(e){if(oThis.oTileData.bIsStaticImage)return;oThis.oNotifier.Notify(oThis,"scale","up");oThis.oCanvasDim=utils.getXY(oThis.oCanvas);var oScrolls=utils.getScrolls();var dx=oThis.oCanvasDim.x+oThis.oCanvasDim.w/2-(e.clientX+oScrolls.x);var dy=oThis.oCanvasDim.y+oThis.oCanvasDim.h/2-(e.clientY+oScrolls.y);oThis.oDnd.dnd.MoveBy(dx,dy);});}
oThis.oNotifier.Notify(oThis,"picture-update","");},null);this.oNotifier.setListener(oThis,"picture-update",function(){var oTileData=oThis.oTileData;utils.removeChildren(oThis.oDnd);oThis.bFirstTimeDraw=false;oThis.oDnd.style.width=oTileData.oPicture.w+"px";oThis.oDnd.style.height=oTileData.oPicture.h+"px";var oFitImg=utils.getNextSibling(oThis.oDnd,"IMG");if(oFitImg){while(true){if(oFitImg){oThis.oCanvas.removeChild(oFitImg);oFitImg=utils.getNextSibling(oThis.oDnd,"IMG");}else
break;}}
if(oThis.oTileData.bIsStaticImage){oThis.oCanvas.className="viewport-static-image";setTimeout(function(){var oImg=document.createElement("img");oImg.setAttribute("src",oThis.oTileData.GetFitUrl());oImg.setAttribute("alt","");var w=oTileData.oPicture.w;var h=oTileData.oPicture.h;var x=false;if(w>oTileData.oViewport.w){w=oTileData.oViewport.w;h=h*w/oTileData.oPicture.w;if(h>oTileData.oViewport.h){h=oTileData.oViewport.h;w=h*oTileData.oPicture.w/oTileData.oPicture.h;}}else if(h>oTileData.oViewport.h){h=oTileData.oViewport.h;w=w*h/oTileData.oPicture.h;if(w>oTileData.oViewport.w){w=oTileData.oViewport.w;h=w*oTileData.oPicture.h/oTileData.oPicture.w;}}
oImg.setAttribute("width",w);oImg.setAttribute("height",h);oImg.className="nodrag";oImg.style.position="absolute";oImg.style.top=((oTileData.oViewport.h-h)/2)+"px";oImg.style.left=((oTileData.oViewport.w-w)/2)+"px";oThis.bForceRedraw=false;oThis.oCanvas.appendChild(oImg);utils.addEvent(oImg,"click",function(e){oThis.oTileData.bIsStaticImage=false;oThis.oTileData.iScaleIndex--;if(oThis.oTileData.iScaleIndex<0){oThis.oTileData.iScaleIndex=0;}
var oScrolls=utils.getScrolls();var oDim=utils.getXY(this);oThis.oTileData.oViewport.cx=(oScrolls.x+e.clientX-oDim.x)/oDim.w;oThis.oTileData.oViewport.cy=(oScrolls.y+e.clientY-oDim.y)/oDim.h;oThis.oNotifier.Notify(oThis,"scale",oThis.oTileData.iScaleIndex);});},30);}else{if(oTileData.oPicture.w<=oTileData.oViewport.w&&oTileData.oPicture.h<=oTileData.oViewport.h){utils.addClass(oThis.oCanvas,"static");oThis.oDnd.dnd.constraint.horiz=false;oThis.oDnd.dnd.constraint.vert=false;}else{utils.removeClass(oThis.oCanvas,"viewport-static-image");utils.removeClass(oThis.oCanvas,"static");utils.addClass(oThis.oCanvas,"viewport");if(oTileData.oPicture.w<=oTileData.oViewport.w){utils.addClass(oThis.oCanvas,"half-static");utils.addClass(oThis.oDnd,"horiz");oThis.oDnd.dnd.constraint.horiz=false;}else{utils.removeClass(oThis.oDnd,"horiz");oThis.oDnd.dnd.constraint.horiz=true;}
if(oTileData.oPicture.h<=oTileData.oViewport.h){utils.addClass(oThis.oCanvas,"half-static");utils.addClass(oThis.oDnd,"vert");oThis.oDnd.dnd.constraint.vert=false;}else{utils.removeClass(oThis.oDnd,"vert");oThis.oDnd.dnd.constraint.vert=true;}}
oThis.Draw();oThis.bForceRedraw=true;oThis.oTileData.oPicture.y=parseInt(oTileData.oViewport.h/2
-oTileData.oPicture.h*oTileData.oViewport.cy);var tt=oTileData.oViewport.h-oTileData.oPicture.h;if(oThis.oTileData.oPicture.y<tt)
oThis.oTileData.oPicture.y=tt;if(oThis.oTileData.oPicture.y>0)oThis.oTileData.oPicture.y=0;oThis.oTileData.oPicture.x=parseInt(oTileData.oViewport.w/2
-oTileData.oPicture.w*oTileData.oViewport.cx);if(oTileData.oViewport.w/2>oTileData.oPicture.w*(1-oThis.oTileData.oViewport.cx))
oThis.oTileData.oPicture.x=oTileData.oViewport.w-oTileData.oPicture.w;if(oThis.oTileData.oPicture.x>0)oThis.oTileData.oPicture.x=0;oThis.oDnd.style.left=oThis.oTileData.oPicture.x+"px";oThis.oDnd.style.top=oThis.oTileData.oPicture.y+"px";}},null);this.oNotifier.setListener(this,"pan-moved",function(oListener,oComment){var top=(-oThis.oTileData.oPan.y)*oThis.oTileData.fPicturePanorama;var left=(-oThis.oTileData.oPan.x)*oThis.oTileData.fPicturePanorama;oThis.oDnd.dnd.Move(left,top);},null);this.oNotifier.setListener(this,"panorama-clicked",function(oListener,oCoord){var top=(-oCoord.y+oThis.oTileData.oPan.h/2)*oThis.oTileData.fPicturePanorama;var left=(-oCoord.x+oThis.oTileData.oPan.w/2)*oThis.oTileData.fPicturePanorama;oThis.oDnd.dnd.Move(left,top);},null);}
Tile.prototype.x_CenterUpdate=function(){this.oTileData.oViewport.cx=(this.oTileData.oViewport.w/2-this.oTileData.oPicture.x)/this.oTileData.oPicture.w;this.oTileData.oViewport.cy=(this.oTileData.oViewport.h/2-this.oTileData.oPicture.y)/this.oTileData.oPicture.h;}
Tile.prototype.Draw=function(){var oThis=this;var oTileData=this.oTileData;this.iColsInPicture=Math.ceil(oTileData.oPicture.w/oTileData.oTile.w);this.iRowsInPicture=Math.ceil(oTileData.oPicture.h/oTileData.oTile.h);this.iColsInViewport=Math.ceil(oTileData.oViewport.w/oTileData.oTile.w);this.iRowsInViewport=Math.ceil(oTileData.oViewport.h/oTileData.oTile.h);this.oDnd.dnd.Drag=function(){clearTimeout(oThis.Timer);oThis.Timer=setTimeout(function(){x_DrawTile();oThis.x_CenterUpdate();},15);}
this.oDnd.dnd.Drag();function x_DrawTile(){function x_DrawFill(row,col,src,resize){var oImg=document.getElementById(oTileData.GetTileId(row,col))
if(oImg){return;}
var iLeft=oTileData.oTile.w*col;if(resize){oImg=document.createElement("div");oImg.className="tile-fill";oImg.style.width=oThis.oTileData.oTile.w+"px";oImg.style.height=oThis.oTileData.oTile.h+"px";oImg.innerHTML="&nbsp;";}else{oImg=document.createElement("img");oImg.setAttribute("src",src);oImg.setAttribute("alt","");}
oImg.style.position="absolute";oImg.style.top=iTop+"px";oImg.style.left=iLeft+"px";oImg.id=oTileData.GetTileId(row,col);oThis.oDnd.appendChild(oImg);}
oThis.oTileData.oPicture.x=parseInt(oThis.oDnd.style.left);oThis.oTileData.oPicture.y=parseInt(oThis.oDnd.style.top);oThis.oNotifier.Notify(oThis,"picture-moved","");var iRowStart=Math.floor((oTileData.oViewport.y-oTileData.oPicture.y)/oTileData.oTile.h)-oThis.Delta;var iColStart=Math.floor((oTileData.oViewport.x-oTileData.oPicture.x)/oTileData.oTile.w)-oThis.Delta;if(iRowStart<1)iRowStart=0;if(iColStart<1)iColStart=0;if(oThis.bFirstTimeDraw&&iRowStart==oThis.iRowStart&&iColStart==oThis.iColStart)
return;oThis.bFirstTimeDraw=true;oThis.iRowStart=iRowStart;oThis.iColStart=iColStart;var iRowEnd=iRowStart+oThis.iRowsInViewport+oThis.Delta;if(iRowEnd>oThis.iRowsInPicture-1)iRowEnd=oThis.iRowsInPicture-1;var iColEnd=iColStart+oThis.iColsInViewport+oThis.Delta;if(iColEnd>oThis.iColsInPicture-1)iColEnd=oThis.iColsInPicture-1;var r=iRowStart-4*oThis.Delta;if(r<0)r=0;var c=iColStart-4*oThis.Delta;if(c<0)c=0;for(var row=r;row<iRowEnd+4*oThis.Delta;row++){var iTop=oThis.oTileData.oTile.h*row;for(var col=c;col<iColEnd+4*oThis.Delta;col++){if(row>=iRowStart&&row<=iRowEnd&&col>=iColStart&&col<=iColEnd){x_DrawFill(row,col,oTileData.GetTileUrl(row,col));}else{var oImg=document.getElementById(oTileData.GetTileId(row,col));if(oImg){try{oThis.oDnd.removeChild(oImg);}catch(e){;;}}}}}}
oThis.oNotifier.Notify(oThis,"picture-is-drawn","");}
function Panorama(TileData,oNotifier){var oThis=this;this.oTileData=TileData;this.oNotifier=oNotifier;this.oCanvas=document.createElement("div");this.oCanvas.className="panorama";this.oCanvas.ondrag=function(){return false;};this.oCanvas.onselectstart=function(){return false;};oThis.oCanvas.style.visibility="hidden";this.oPan=new Pan(oThis.oTileData,oThis.oNotifier);this.oNotifier.setListener(oThis,"picture-update",function(){if(oThis.oTileData.bIsStaticImage){oThis.oCanvas.style.visibility="hidden";return;}
if(oThis.oTileData.oPanorama.bIsVisible){oThis.oCanvas.style.visibility="visible";}else{oThis.oCanvas.style.visibility="hidden";}
utils.removeChildren(oThis.oCanvas);var iCanvasWidth=2+oThis.oTileData.oPanorama.w+oThis.oTileData.oPanorama.border*2;var iCanvasHeight=2+oThis.oTileData.oPanorama.h+oThis.oTileData.oPanorama.border*2;oThis.oCanvas.style.position="absolute";oThis.oCanvas.style.width=iCanvasWidth+"px";oThis.oCanvas.style.height=iCanvasHeight+"px";var top=-(iCanvasHeight+oThis.oTileData.iWinBorder);var left=-(iCanvasWidth+oThis.oTileData.iWinBorder);if(oThis.oCanvas.offsetParent){top+=oThis.oCanvas.offsetParent.offsetHeight;left+=oThis.oCanvas.offsetParent.offsetWidth;}
oThis.oCanvas.style.top=top+"px";oThis.oCanvas.style.left=left+"px";oThis.oPanorama=document.createElement("div");oThis.oPanorama.style.position="absolute";oThis.oTileData.oPanorama.x=oThis.oTileData.oPanorama.border;oThis.oTileData.oPanorama.y=oThis.oTileData.oPanorama.border;oThis.oPanorama.style.top=oThis.oTileData.oPanorama.y+"px";oThis.oPanorama.style.left=oThis.oTileData.oPanorama.x+"px";oThis.oPanorama.style.width=oThis.oTileData.oPanorama.w+"px";oThis.oPanorama.style.height=oThis.oTileData.oPanorama.h+"px";var oImg=oThis.oTileData.oPanorama.img.cloneNode(false);oImg.ondrag=function(){return false;};oImg.onselectstart=function(){return false;};oThis.oPanorama.appendChild(oImg);oImg.setAttribute("width",oThis.oTileData.oPanorama.w);oImg.setAttribute("height",oThis.oTileData.oPanorama.h);oThis.oPanorama.appendChild(oThis.oPan.oCanvas);setTimeout(function(){oThis.oCanvas.appendChild(oThis.oPanorama);},10);utils.addEvent(oThis.oPanorama,"click",function(e){var oTarget=utils.getTargetObj(e);if(oTarget.tagName!="IMG")return;oThis.oCanvasDim=utils.getXY(oThis.oCanvas);var oScrolls=utils.getScrolls();var x=(e.clientX+oScrolls.x)
-oThis.oCanvasDim.x-oThis.oTileData.oPanorama.border
-oThis.oTileData.iWinBorder;var y=(e.clientY+oScrolls.y)
-oThis.oCanvasDim.y-oThis.oTileData.oPanorama.border
-oThis.oTileData.iWinBorder;oThis.oNotifier.Notify(this,"panorama-clicked",{x:x,y:y});});},null);this.oNotifier.setListener(this,"switch",function(oListener,oComment){if(oThis.oTileData.oPanorama.bIsVisible){oThis.oCanvas.style.visibility="visible";}else{oThis.oCanvas.style.visibility="hidden";}},null);}
function Pan(TileData,oNotifier){var oThis=this;this.oTileData=TileData;this.oNotifier=oNotifier;this.Timer=null;this.oCanvas=document.createElement("div");this.oCanvas.style.position="absolute";var iBorderWidth=2;this.oCanvas.style.borderTopWidth=this.oCanvas.style.borderBottomWidth=this.oCanvas.style.borderLeftWidth=this.oCanvas.style.borderRightWidth=iBorderWidth+"px";this.oCanvas.className="pan";this.oCanvas.dnd=new Dnd(this.oCanvas,"absolute");this.oCanvas.style.visibility="hidden";this.oCanvas.dnd.Drag=function(){oThis.Timer=setTimeout(function(){oThis.oTileData.oPan.x=parseInt(oThis.oCanvas.style.left);oThis.oTileData.oPan.y=parseInt(oThis.oCanvas.style.top);oThis.oNotifier.Notify(this,"pan-moved","");},10);}
this.oTileData.oPan.x=this.oTileData.oPan.y=0;this.oNotifier.setListener(this,"picture-update",function(oListener,oComment){if(oThis.oTileData.bIsStaticImage){oThis.oCanvas.style.visibility="hidden";return;}
if(oThis.oTileData.oPanorama.bIsVisible){oThis.oCanvas.style.visibility="visible";}else{oThis.oCanvas.style.visibility="hidden";}
oThis.oCanvas.style.width=(oThis.oTileData.oPan.w-2*iBorderWidth)+"px";oThis.oCanvas.style.height=(oThis.oTileData.oPan.h-2*iBorderWidth)+"px";},null);this.oNotifier.setListener(this,"picture-moved",function(oListener,oComment){oThis.oTileData.oPan.y=parseInt(-oThis.oTileData.oPicture.y/oThis.oTileData.fPicturePanorama);oThis.oTileData.oPan.x=parseInt(-oThis.oTileData.oPicture.x/oThis.oTileData.fPicturePanorama);oThis.oCanvas.style.top=oThis.oTileData.oPan.y+"px";oThis.oCanvas.style.left=oThis.oTileData.oPan.x+"px";},null);this.oNotifier.setListener(this,"switch",function(oListener,oComment){if(oThis.oTileData.oPanorama.bIsVisible){oThis.oCanvas.style.visibility="visible";}else{oThis.oCanvas.style.visibility="hidden";}},null);}
function PanoramaSwitcher(TileData,oNotifier){var oThis=this;this.oTileData=TileData;this.oNotifier=oNotifier;oThis.PanoramaSwitcher=null;this.oCanvas=document.createElement("div");this.oCanvas.style.visibility="hidden";this.oCanvas.style.position="absolute";this.oCanvas.className="pan-switcher";this.oCanvas.innerHTML="&nbsp;";x_updateStatus();utils.addEvent(this.oCanvas,"click",function(){oThis.oTileData.oPanorama.bIsVisible=!oThis.oTileData.oPanorama.bIsVisible;oThis.oNotifier.Notify(this,"switch",oThis.oTileData.oPanorama.bIsVisible);x_updateStatus();},false);function x_updateStatus(){if(oThis.oTileData.oPanorama.bIsVisible){utils.addClass(oThis.oCanvas,"pan-switcher-close");oThis.oCanvas.title="Hide Panorama View";}else{utils.removeClass(oThis.oCanvas,"pan-switcher-close");oThis.oCanvas.title="Show Panorama View";}}
this.oNotifier.setListener(oThis,"picture-update",function(){if(oThis.oTileData.bIsStaticImage){oThis.oCanvas.style.visibility="hidden";return;}
oThis.oCanvas.style.visibility="visible";var top=-(parseInt(oThis.oCanvas.offsetHeight)+oThis.oTileData.iWinBorder);var left=-(parseInt(oThis.oCanvas.offsetWidth)+oThis.oTileData.iWinBorder);if(oThis.oCanvas.offsetParent){top+=oThis.oCanvas.offsetParent.offsetHeight;left+=oThis.oCanvas.offsetParent.offsetWidth;}
oThis.oCanvas.style.top=top+"px";oThis.oCanvas.style.left=left+"px";},null);}